version: "3.8"

services: 
  db:
    image: mongo:latest
    container_name: db
    volumes: 
      - ./mongo/db:/data/db

  nginx:
    image: nginx:latest
    container_name: proxy
    volumes: 
      - ./proxy/default.conf:/etc/nginx/conf.d/default.conf
    ports: 
      - 80:80
    depends_on: 
      - back_end

  front_end: 
    image: node:latest
    container_name: front
    volumes: 
    - ./front-end:/front-end
    command: bash -c "cd /front-end && npm i && npm start"
    ports: 
    - 8080:3000

  back_end:
    image: node:8.1
    container_name: back
    volumes: 
      - ./back-end:/back-end
    command: bash -c "cd /back-end && npm i && node app";
    depends_on: 
      - db